version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
    links:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/image/php.Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./src:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql
    container_name: ${APP_NAME}_mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
